const mongoose = require('mongoose');


// A short-lived token generated by a dietitian for a specific lead.
// The client opens the shareable URL (/diet-onboarding?token=xxx) without any login.
const DietOnboardingTokenSchema = new mongoose.Schema(
 {
   token: { type: String, required: true, unique: true, index: true },


   // The lead this token belongs to (can be a real Lead._id or a synthetic ObjectId)
   leadId: { type: mongoose.Schema.Types.ObjectId, required: true, index: true },


   // Prefill data shown to the client when they open the URL
   clientName:  { type: String, default: '' },
   clientPhone: { type: String, default: '' },


   // Who generated the link
   createdBy: { type: String, default: '' },


   // Token expires 30 days after generation; null = never expires
   expiresAt: { type: Date, default: () => new Date(Date.now() + 30 * 24 * 60 * 60 * 1000) },


   // Once the client submits their profile this becomes true
   used: { type: Boolean, default: false },
   usedAt: { type: Date },
 },
 { timestamps: true }
);


// Auto-expire index so MongoDB removes old docs automatically
DietOnboardingTokenSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });


module.exports = mongoose.model('DietOnboardingToken', DietOnboardingTokenSchema);



